K:
   rows: 3
   cols: 3
   dt: d
   data: [ 3.3112734499444791e+03, 0., 6.8998248444736601e+02, 0.,
       3.2240712043235176e+03, 3.8412116837794224e+02, 0., 0., 1. ]
D:
   rows: 1
   cols: 5
   dt: d
   data: [ -1.4977421054844131e+00, 3.0708652349007988e+00,
       1.1789665067175169e-01, -4.0539193246590405e-03,
       -1.4856365965816121e+01 ]
